SELECT t.APNT_NO, p.PT_NAME, p.PT_NO, t.MCDP_CD, d.DR_NAME, t.APNT_YMD
FROM (SELECT *
      FROM APPOINTMENT a
      WHERE DATE_FORMAT(APNT_YMD, '%Y-%m-%d') = '2022-04-13'
      AND APNT_CNCL_YN = 'N'
     ) as t
JOIN PATIENT p ON t.PT_NO = p.PT_NO
JOIN DOCTOR d on t.MDDR_ID = d.DR_ID
WHERE t.MCDP_CD = 'CS'
ORDER BY t.APNT_YMD ASC